image: memmos.laas.fr:5000/recreation/navires

build:
  stage: build
  script: cargo build

test:
  stage: test
  script: cargo llvm-cov

format:
  before_script:
    - rustup component add clippy rustfmt
  script:
    - cargo clippy -- -D warnings
    - cargo fmt --all -- --check
