image: rust:slim

format:
  before_script:
    - rustup component add clippy rustfmt
  script:
    - cargo clippy -- -D warnings
    - cargo fmt --all -- --check

build:
  stage: build
  script: cargo build

test:
  stage: test
  script: cargo test
