test:
  image: rust:slim
  before_script:
    - apt-get update -qqy && apt-get install -qqy cmake g++ pkg-config jq libcurl4-openssl-dev libelf-dev libdw-dev binutils-dev libiberty-dev
    - rustup component add clippy rustfmt
    - cargo install cargo-kcov
    - cargo kcov --print-install-kcov-sh | sh
  script:
    - cargo build
    - cargo test
    - cargo clippy -- -D warnings
    - cargo fmt --all -- --check
    - cargo kcov
    - grep percent_covered target/cov/kcov-merged/coverage.json | tail -n1
