image: rust:slim

variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/.cargo

cache:
 paths:
   - target
   - .cargo

build:
  stage: build
  script: cargo build

test:
  stage: test
  script: cargo test

format:
  before_script:
    - rustup component add clippy rustfmt
  script:
    - cargo clippy -- -D warnings
    - cargo fmt --all -- --check
